using System;
using System.Collections.Generic;

namespace RestfulApi.Model.Models
{
    public partial class DAT_BPOS
    {
        public int ZAEHLER { get; set; }
        public short Z_AKUNDE { get; set; }
        public Nullable<System.DateTime> DAT_LASTMOD { get; set; }
        public string LISTE_KZ { get; set; }
        public string EDV1 { get; set; }
        public string NPARM_RESERVE { get; set; }
        public short W_STATUS { get; set; }
        public int LOG_Status { get; set; }
        public Nullable<System.DateTime> DAT_STATUS { get; set; }
        public string MANDANT { get; set; }
        public string VS_HIER1 { get; set; }
        public string VS_HIER2 { get; set; }
        public string VS_HIER3 { get; set; }
        public string BS_HIER2 { get; set; }
        public string BS_HIER3 { get; set; }
        public Nullable<int> Z_IMPORT { get; set; }
        public int Z_LFT { get; set; }
        public int Z_BEST { get; set; }
        public Nullable<int> Z_VS_HIER2 { get; set; }
        public Nullable<int> Z_VS_HIER3 { get; set; }
        public string BP_TXD { get; set; }
        public string BP_TXX { get; set; }
        public string BP_TXX1 { get; set; }
        public string BP_TXX2 { get; set; }
        public string BP_TXX3 { get; set; }
        public float BP_MENGE { get; set; }
        public float VS_MENGE { get; set; }
        public float BP_MENGE2 { get; set; }
        public short W_BP_MENGENEINHEIT { get; set; }
        public short W_BP_MENGENEINHEIT2 { get; set; }
        public decimal WERT { get; set; }
        public string ISO_WAEHRUNGWERT { get; set; }
        public Nullable<float> GEWICHT_KG { get; set; }
        public string VS_GEWICHT_KG { get; set; }
        public Nullable<System.DateTime> DAT_LIEFER_PLAN { get; set; }
        public Nullable<System.DateTime> DAT_LIEFER_ERWARTET { get; set; }
        public Nullable<System.DateTime> DAT_LIEFER_PLAN2 { get; set; }
        public Nullable<System.DateTime> DAT_ABNAHME_PLAN { get; set; }
        public Nullable<System.DateTime> DAT_ABNAHME_ERWARTET { get; set; }
        public int Z_LFT_ABHOL { get; set; }
        public string ABHOL_ANSPRECH { get; set; }
        public string ABHOL_TELEFON1 { get; set; }
        public string ABHOL_TELEFON2 { get; set; }
        public string ABHOL_FAX { get; set; }
        public string ABHOL_EMAIL { get; set; }
        public string ABHOL_LADEZEITEN { get; set; }
        public string ABHOL_BEMERKUNG { get; set; }
        public int Z_LFT_ZIEL { get; set; }
        public string ZIEL_ANSPRECH { get; set; }
        public string ZIEL_TELEFON1 { get; set; }
        public string ZIEL_TELEFON2 { get; set; }
        public string ZIEL_FAX { get; set; }
        public string ZIEL_EMAIL { get; set; }
        public string ZIEL_LADEZEITEN { get; set; }
        public string ZIEL_BEMERKUNG { get; set; }
        public int Z_USER { get; set; }
        public int Z_USER_TK_BESTELLUNG { get; set; }
        public int Z_USER_TK_CONFIRM { get; set; }
        public string ABMESS1 { get; set; }
        public string ABMESS2 { get; set; }
        public string ABMESS3 { get; set; }
        public string ABMESS4 { get; set; }
        public string ABMESS5 { get; set; }
        public string ABMESS6 { get; set; }
        public string ZEICHNUNGS_NR { get; set; }
        public string ZEICHNUNGS_POS { get; set; }
        public string ZEICHNUNGS_TXX { get; set; }
        public string NETZPLAN_NR { get; set; }
        public string NETZPLAN_POS { get; set; }
        public string NETZPLAN_TXX { get; set; }
        public string TX_INCOTERM2000 { get; set; }
        public string INCO_ZUSATZ { get; set; }
        public string BAUGRUPPE_NR { get; set; }
        public string BAUGRUPPE_POS { get; set; }
        public string MATERIAL_NR { get; set; }
        public string TPLATZ_NR { get; set; }
        public string TPLATZ_POS { get; set; }
        public string GEFAHRGUT_KLASSE { get; set; }
        public string GEFAHRGUT_UNNR { get; set; }
        public string EMR_TAG { get; set; }
        public string EMR_TEILE { get; set; }
        public string ROHRTEILE { get; set; }
        public string TON { get; set; }
        public string PRUEFKOMMENTAR { get; set; }
        public string CLIENTCODE { get; set; }
        public string PRPS_POSID { get; set; }
        public string KOMMISSION { get; set; }
        public int NPARM_LT_NR { get; set; }
        public string WERKSTOFF { get; set; }
        public string KENNWERTE { get; set; }
        public string KKS_NR { get; set; }
        public string STAT_WAREN_NR { get; set; }
        public string BESTAETIGUNG_LFT { get; set; }
        public string PKEY_AKUNDE { get; set; }
        public Nullable<float> PROZ_WERT { get; set; }
        public Nullable<int> W_TEXTE { get; set; }
        public string NORM { get; set; }
        public string ABNAHME { get; set; }
        public string LISTE_UNITS { get; set; }
        public string ABW_ADRESSE { get; set; }
        public string EK_TXX { get; set; }
        public Nullable<System.DateTime> DAT_WIEDERVORLAGE { get; set; }
        public string BEMERKUNG_VERZUG { get; set; }
        public string BEMERKUNG_EXPEDITING { get; set; }
        public short VERZUGSDAUER_WO { get; set; }
        public string LISTE_DATEIEN { get; set; }
        public string LISTE_AUFTRAGSNR { get; set; }
    }
}
