using System;
using System.Collections.Generic;

namespace RestfulApi.Model.Models
{
    public partial class DAT_KISTEN
    {
        public int ZAEHLER { get; set; }
        public short Z_AKUNDE { get; set; }
        public System.DateTime DAT_LASTMOD { get; set; }
        public string LISTE_KZ { get; set; }
        public string EDV1 { get; set; }
        public string NPARM_RESERVE { get; set; }
        public short W_STATUS { get; set; }
        public int LOG_Status { get; set; }
        public System.DateTime DAT_STATUS { get; set; }
        public string MANDANT { get; set; }
        public string VS_HIER1 { get; set; }
        public string VS_HIER2 { get; set; }
        public string VS_HIER3 { get; set; }
        public string BS_HIER2 { get; set; }
        public string BS_HIER3 { get; set; }
        public int Z_LFT { get; set; }
        public int Z_SUMMARY { get; set; }
        public int Z_CONTAINER { get; set; }
        public short Z_HERSTELLER { get; set; }
        public short Z_VSAUFTRAG { get; set; }
        public int Z_VSBEREIT { get; set; }
        public Nullable<short> W_ART { get; set; }
        public Nullable<short> W_ART_TRANSPORT { get; set; }
        public Nullable<short> W_FAKTSTATUS { get; set; }
        public Nullable<short> W_FAKTHERSTELLER { get; set; }
        public Nullable<short> W_KATEGORIE { get; set; }
        public short W_STANDORT { get; set; }
        public short W_FERTIGORT { get; set; }
        public Nullable<short> W_ORT_VP { get; set; }
        public Nullable<int> W_ART_BESTELLUNG { get; set; }
        public Nullable<int> W_TEXTE { get; set; }
        public Nullable<short> W_ART_LAGERBEDINGUNG { get; set; }
        public string BARCODE { get; set; }
        public string KOLLINUMMER { get; set; }
        public string LAGERORT1 { get; set; }
        public string LAGERORT2 { get; set; }
        public string LAGERORT3 { get; set; }
        public string KONS_NR { get; set; }
        public string KONS_FERTIGTEXT { get; set; }
        public string KONS_TEXT1 { get; set; }
        public string KONS_TEXT2 { get; set; }
        public string KONS_TEXT3 { get; set; }
        public string KONS_TEXT4 { get; set; }
        public Nullable<short> KONS_KORRMON { get; set; }
        public string KONS_BAUART { get; set; }
        public float ABMESS1_MM { get; set; }
        public float ABMESS2_MM { get; set; }
        public float ABMESS3_MM { get; set; }
        public float BRUTTO_KG { get; set; }
        public float NETTO_KG { get; set; }
        public float TARA_KG { get; set; }
        public string INHALT_TXD { get; set; }
        public string INHALT_TXX { get; set; }
        public string INHALT_TXX2 { get; set; }
        public string SOLLVPART { get; set; }
        public Nullable<System.DateTime> DAT_SOLLVP { get; set; }
        public Nullable<System.DateTime> DAT_KONSTRUKTION { get; set; }
        public Nullable<System.DateTime> DAT_FERTIGUNG { get; set; }
        public Nullable<System.DateTime> DAT_ABRUF { get; set; }
        public Nullable<System.DateTime> DAT_EINGANGZV { get; set; }
        public Nullable<System.DateTime> DAT_VERSAND { get; set; }
        public Nullable<System.DateTime> DAT_FAKTURIERT { get; set; }
        public string NEUTRAL05 { get; set; }
        public string NEUTRAL10 { get; set; }
        public string NEUTRAL20 { get; set; }
        public string NEUTRAL30 { get; set; }
        public Nullable<float> WERT { get; set; }
        public string ISO_WAEHRUNGWERT { get; set; }
        public string GEFAHRGUT_KLASSE { get; set; }
        public string GEFAHRGUT_UNNR { get; set; }
        public string RECHNUM_VP { get; set; }
        public Nullable<int> LIEFERSCHEIN_BAU { get; set; }
        public string LAGERORT_BAUSTELLE { get; set; }
        public string BEMERKUNG_BAUSTELLE { get; set; }
        public Nullable<int> PKEY_BOXCAD { get; set; }
        public string PKEY_AKUNDE { get; set; }
        public Nullable<float> PROZ_WERT { get; set; }
        public Nullable<System.DateTime> DAT_EINGANG_BAUSTELLE { get; set; }
        public Nullable<int> W_STATUS_BAUSTELLE { get; set; }
        public Nullable<short> ANZ_VERLADUNGEN { get; set; }
        public Nullable<short> LT_ANZ { get; set; }
        public string SAP_SPRACHE { get; set; }
        public string BEMERKUNG { get; set; }
        public string BARCODE_EXTERN { get; set; }
        public string KONTO { get; set; }
        public string FAKTRENUM { get; set; }
        public Nullable<int> ANZ_KARTONS { get; set; }
        public string ABRECHNUNGSHINWEIS { get; set; }
        public string ABTEILUNG { get; set; }
        public string WE_NR { get; set; }
        public string KOSTENSTELLE { get; set; }
        public Nullable<System.DateTime> DAT_LAGERZEITRAUM_VON { get; set; }
        public Nullable<System.DateTime> DAT_LAGERZEITRAUM_BIS { get; set; }
        public Nullable<System.DateTime> DAT_LAGERABGERECHNET_VON { get; set; }
        public Nullable<System.DateTime> DAT_LAGERABGERECHNET_BIS { get; set; }
        public string KOLLINUMMER_INTERN { get; set; }
        public int Z_LFT_ZIEL { get; set; }
        public string ZIEL_ANSPRECH { get; set; }
        public string ZIEL_TELEFON1 { get; set; }
        public string ZIEL_TELEFON2 { get; set; }
        public string ZIEL_FAX { get; set; }
        public string ZIEL_EMAIL { get; set; }
        public string ZIEL_LADEZEITEN { get; set; }
        public string ZIEL_BEMERKUNG { get; set; }
        public string TOKEN_BAU { get; set; }
        public string TOKEN_AKUNDE { get; set; }
        public string TOKEN_VP { get; set; }
        public Nullable<System.DateTime> DAT_FAKTURIERT_BAU { get; set; }
        public Nullable<System.DateTime> DAT_FAKTURIERT_AKUNDE { get; set; }
        public Nullable<System.DateTime> DAT_FAKTURIERT_VP { get; set; }
        public Nullable<System.DateTime> DAT_FAKTURIERT_ENDK { get; set; }
        public string RECHNUM_BAU { get; set; }
        public string RECHNUM_AKUNDE { get; set; }
        public string RECHNUM_ENDK { get; set; }
        public Nullable<short> W_FAKTSTATUS_BAU { get; set; }
        public Nullable<short> W_FAKTSTATUS_AKUNDE { get; set; }
        public Nullable<short> W_FAKTSTATUS_VP { get; set; }
        public Nullable<short> W_FAKTSTATUS_ENDK { get; set; }
        public Nullable<short> W_ORT_BAU { get; set; }
        public Nullable<int> LIEFERSCHEIN_AKUNDE { get; set; }
        public Nullable<int> LIEFERSCHEIN_VP { get; set; }
        public Nullable<int> LIEFERSCHEIN_ENDK { get; set; }
        public short ANZ_PRO_BUND { get; set; }
    }
}
